# Deep Learning with PythonProgramming.net

I have changed values to try this deep learning tensor out. First we need to import the PyTorch package.

Then to create basic tensors, or matrices, we will initiate two new variables x and y:

In [2]:
import torch

x = torch.Tensor([4, 2])
y = torch.Tensor([2, 3])

print(x*y)

tensor([8., 6.])


In [3]:
x = torch.zeros([4, 2])

print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
y = torch.zeros([2, 3])

print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.Tensor([4, 2])
y = torch.Tensor([2, 3])

print(x / y)

tensor([2.0000, 0.6667])


In [ ]:
y = torch.rand([2, 5])
print(y)

In [13]:
y.view([1, 10])

tensor([[0.6656, 0.7540, 0.5123, 0.9277, 0.3719, 0.5809, 0.7249, 0.2490, 0.9031,
         0.8241]])

Re-assigning variable y

In [14]:
y = y.view([1,10])
y

tensor([[0.6656, 0.7540, 0.5123, 0.9277, 0.3719, 0.5809, 0.7249, 0.2490, 0.9031,
         0.8241]])

In [10]:
import torch

x = torch.rand([2, 1])
y = torch.rand([3, 5])
z = torch.rand([1, 4])

print(x)
print(y)
print(z)


tensor([[0.8050],
        [0.9310]])
tensor([[0.8904, 0.3607, 0.3248, 0.8599, 0.5997],
        [0.3130, 0.5593, 0.1836, 0.5704, 0.0490],
        [0.6119, 0.1997, 0.8047, 0.4561, 0.2632]])
tensor([[0.8178, 0.6957, 0.8303, 0.8372]])
