In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
iris_data = datasets.load_iris()

In [3]:
X = iris_data.data[:, :]
y = np.array(iris_data.target, dtype=int)

In [8]:
print(X[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [9]:
print(y[:5])

[0 0 0 0 0]


In [12]:
iris_df = pd.DataFrame(iris_data)

ValueError: Per-column arrays must each be 1-dimensional

In [13]:
iris_data.columns

AttributeError: columns